# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2da637a69ed789953d7147554fa63a2b5d2784e2755ec8a03a63bd668afcb690da6dd700a20faaa9608926409d754c3b46de6e986985e152a7239807761df8a5

test:
  secret_key_base: f4bcc222ae7019d8f9b955d37f8499a0985889a673d342e5523a7cb65a221d5acbe4c8978e6ef83c41f76bf8933efd0c9b47fef301297dfccad1f146a681bb7c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
